import ProductImg from '@/assets/images/product1.png';
export const products = [
    {
        id: 1,
        name: 'Product 1',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Biography',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 2,
        name: 'Product 2',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Biography',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 20,
        sales: 9,
        stock: 11,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 3,
        name: 'Product 3',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Philosophy',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 18,
        sales: 8,
        stock: 10,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 4,
        name: 'Product 4',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Science',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 5,
        name: 'Product 5',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Science',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 6,
        name: 'Product 6',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Fiction',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 16,
        sales: 4,
        stock: 12,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 7,
        name: 'Product 7',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Business',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 30,
        sales: 13,
        stock: 20,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 8,
        name: 'Product 8',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Business',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 9,
        name: 'Product 9',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Biography',
        dateUpdate: '2023-10-01',
        country: 'Business',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    }
    ,    
    {
        id: 10,
        name: 'Product 10',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Fiction',
        dateUpdate: '2023-10-01',
        country: 'Business',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 11,
        name: 'Product 11',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Fiction',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 12,
        name: 'Product 12',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Fiction',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    }
]