import ProductImg from '@/assets/images/product1.png';
import ProductImg2 from '@/assets/images/product2.png';
import ProductImg3 from '@/assets/images/product3.png';
import ProductImg4 from '@/assets/images/product4.png';
import ProductImg5 from '@/assets/images/product5.png';

export const products = [
    {
        id: 1,
        name: 'Product 1',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Biography',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 2,
        name: 'Product 2',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Biography',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 20,
        sales: 9,
        stock: 11,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 3,
        name: 'Product 3',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg2,
        genre: 'Philosophy',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 18,
        sales: 8,
        stock: 10,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 4,
        name: 'Product 4',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg3,
        genre: 'Science',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 5,
        name: 'Product 5',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg3,
        genre: 'Science',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 6,
        name: 'Product 6',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg4,
        genre: 'Fiction',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 16,
        sales: 4,
        stock: 12,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 7,
        name: 'Product 7',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg5,
        genre: 'Business',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 30,
        sales: 13,
        stock: 20,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 8,
        name: 'Product 8',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg5,
        genre: 'Business',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 9,
        name: 'Product 9',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Biography',
        dateUpdate: '2023-150-01',
        country: 'Business',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    }
    ,    
    {
        id: 10,
        name: 'Product 10',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg4,
        genre: 'Fiction',
        dateUpdate: '2023-150-01',
        country: 'Business',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 11,
        name: 'Product 11',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg4,
        genre: 'Fiction',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
        {
        id: 12,
        name: 'Product 12',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg4,
        genre: 'Fiction',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 13,
        name: 'Product 13',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg4,
        genre: 'Fiction',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 14,
        name: 'Product 14',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg4,
        genre: 'Fiction',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 15,
        name: 'Product 15',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Biography',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 16,
        name: 'Product 16',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Biography',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 17,
        name: 'Product 17',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg,
        genre: 'Biography',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 18,
        name: 'Product 18',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg5,
        genre: 'Business',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 19,
        name: 'Product 19',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg5,
        genre: 'Business',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 20,
        name: 'Product 20',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg5,
        genre: 'Business',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 21,
        name: 'Product 21',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg5,
        genre: 'Business',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 22,
        name: 'Product 22',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg3,
        genre: 'Science',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 23,
        name: 'Product 23',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg3,
        genre: 'Science',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 24,
        name: 'Product 24',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg3,
        genre: 'Science',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 25,
        name: 'Product 25',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg3,
        genre: 'Science',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 26,
        name: 'Product 26',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg2,
        genre: 'Philosophy',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 27,
        name: 'Product 27',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg2,
        genre: 'Philosophy',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 28,
        name: 'Product 28',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg2,
        genre: 'Philosophy',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 29,
        name: 'Product 29',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg2,
        genre: 'Philosophy',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    },
            {
        id: 30,
        name: 'Product 30',
        description: 'Description for product 1',
        author: 'Author',
        publisher: 'NXB Kim Đồng',
        price: 100000,
        image: ProductImg2,
        genre: 'Philosophy',
        dateUpdate: '2023-10-01',
        country: 'Viet Nam',
        publicationDate: '2023-09-15',
        count: 10,
        sales: 4,
        stock: 6,  //count - sales
        avgRating: 4.2, 
        totalReviews: 15 
    }
]